### ISSUE TITLE
Failed to install - wrong size for extra data

### ISSUE THREAD

**Issue by olantrust** [flathub/com.hamrick.VueScan#47]
Seems there's a mismatch and a version number or filesize has not been updated on flathub?
For several weeks I'm getting this when trying to install via console:
(When trying to update or install via KDE Discover, get a silent fail too).

flatpak install flathub com.hamrick.VueScan
Looking for matches?

com.hamrick.VueScan permissions:
    ipc                  network       pulseaudio      x11      devices
    file access [1]      tags [2]

    [1] xdg-documents, xdg-pictures
    [2] proprietary

        ID                                  Branch          Remote          Download
 1. [?] com.hamrick.VueScan                 stable          flathub           9.6?MB / 12.5?MB
 2. [ ] com.hamrick.VueScan.Locale          stable          flathub         < 6.3?MB (partial)

Error: Wrong size for extra data https://d2bwyyzfw77fhf.cloudfront.net/vuex6497.tgz
error: Failed to install com.hamrick.VueScan: Wrong size for extra data https://d2bwyyzfw77fhf.cloudfront.net/vuex6497.tgz

**Comment by FakeShemp** [comment]
The app updates several times a day, so flathub has a hard time keeping up always. It's updated at regular intervals.

**Comment by pkh-** [comment]
Hi,

it would be nice to include the international OCR-Files from:

[Supported OCR Languages](https://www.hamrick.com/ocr.html) .

It's sufficient to put them all together into the extra folder (location of the executive bin file).

Thanks. Nice work.

pkh

**Comment by Avanesov79** [comment]
Is there a way to force flatpak to use the downloaded file? Im having the same issue with the exact same file download and it has been almost 3 weeks since the last post. The manual download off the Vuescan website is the same one according to the version number.

**Comment by FakeShemp** [comment]
And that's the problem, all updates use the same version number, so it's impossible to know what to download.

That you're still having problems is weird though, as a bot now handles the updates.

**Comment by FakeShemp** [comment]
Fixed with newest update checker.

**Comment by mnoukhov** [comment]
Still having this issue with Flatpak 1.8.2 on Fedora 33

**Comment by FakeShemp** [comment]
The issue is that the buildbot is down.

**Comment by FONDSMATIVE** [comment]
Hi everybody, 

thanks a lot for all your great work! 

**This issue is still the same! Any new ideas to fix this once and for all?** 
Problem as it was and still is: *Error: wrong size for https://d2bwyyzfw77fhf.cloudfront.net/vuex6497.tgz*

Many thanks again!

**Comment by FakeShemp** [comment]
The issue is that there is a delay between the update of vuescan and the update of the flatpak. Just wait for a bit and it will catch up. There can be nothing done to fix this.

**Comment by sesser** [comment]
20 months later, running into this issue myself. On Ubuntu 20.04.5.

**Comment by FakeShemp** [comment]
The issue is that there is a delay between the update of vuescan and the update of the flatpak.

Just wait a few minutes for the package to update!

**Comment by sesser** [comment]
Just tried it again. Same result. 3 hours... but I see the bot updated the yaml 30 some minutes ago. Seems like a deficiency in flatpack.

**Comment by FakeShemp** [comment]
The package will always need to be built and published before anything can happen. Not sure how you expect that get around that. This has nothing to do with how flatpak works.

https://buildbot.flathub.org/#/builders/2/builds/699

**Comment by sesser** [comment]
Whether it's flatpack, flathub, or some other build bot managing the packages is irrelevant. When the end user types in `flatpack install vuescan` they should expect to install vuescan. 

From a cursory vue (eh, couldn't resist) and my limited knowledge of the flatpack/flathub process, my gut tells me this might be mitigated by simply versioning the filenames. My guess is because it's the same URL and it looks to be validating the size of the archive and there's a lag of when the flathub index gets updated, installs will fail for a period of time until everything is in sync.

**Comment by FakeShemp** [comment]
Feel free to submit a pull request with a fix.

**Comment by kirmaha** [comment]
This is still happening :
`Error: Wrong size for extra data https://d2bwyyzfw77fhf.cloudfront.net/vuex6498.tgz
error: Failed to install com.hamrick.VueScan: Wrong size for extra data https://d2bwyyzfw77fhf.cloudfront.net/vuex6498.tgz`

1. I started trying six hours ago, so I'm wondering if it will take days before I can use it ?
2. After installing, I will want to downgrade to the previous version (as my license stopped just before the last update): will I be able to, or will I encounter that same issue as filenames are not versioned?
3. I'm trying to install the flatpak version because on Debian 12, .deb and .tar.gz versions are either crashing at startup, either not detecting my scan. Which comes from VueScan, since GNOME scan software does detect my scanner. Anyone encounters the same ?

**Comment by JPWhiteHome** [comment]
And here we are years later and same dodo different day.

1. [✗] com.hamrick.VueScan          stable          u          flathub         47.0 MB / 50.9 MB

Error: Wrong size for extra data https://files.hamrick.com/vuex6498.tgz
Updates complete.
error: There were one or more errors

VueScan runs on my system, just won't update. I suppose since it works I can afford to wait for an update.

Fedora Kinoite 43 - 2026-02-11
